kypvalanx/Foundry-VTT-StarWars-SagaEdition

- module/actor/actor-sheet.js
- module/actor/actor.mjs
- system.json
- template.json
* fixed issue where Duros could not be added to a sheet
> * fixed bug that prevented NPC sheets from rendering

- module/actor/actor.js
- templates/actor/actor-sheet.hbs
> fixes #21 talent tree loading and display

- module/actor/actor.js
- template.json
* Use the force now cannot be used untrained
* use the force cannot be trained without the force sensitivity feat
fixes #16
> Fixed Use the force

- module/actor/actor-sheet.js
- module/config.js
* droids now are restricted to 21 points point buy
fixes #24
> Fixed Droid Point Buy

- css/swse.css
- module/actor/health.js
- module/swse.js
- module/util.js
- scss/components/_items.scss
- templates/actor/actor-sheet.hbs
* per level HP is now accurately shown
* a section for item bonuses has been added
fixes #17
> Made Class Health Page more descriptive

- module/actor/actor-sheet.js
- module/actor/actor.js
- module/actor/attribute-handler.js
- templates/actor/actor-sheet.hbs
> fixed issues around the force tab and an issue where the age dialogue would appear when pressing enter

- module/actor/actor.js
- module/prerequisite.js
also fixed issue with prerequisites.js
> * fixed notes on attack rolls

- css/swse.css
- module/actor/actor.js
- module/actor/attack.js
- module/prerequisite.js
- module/swse.js
- module/util.js
- scss/components/_item.scss
- scss/swse.scss
- templates/actor/vehicle/vehicle-attacks-summary.hbs
- templates/item/item-sheet.hbs
- templates/item/parts/summary.hbs
> fixed vehicle attack issue

- css/swse.css
- module/actor/actor.js
- module/actor/attack.js
- module/attribute-helper.js
- module/item/item-sheet.js
- scss/components/_items.scss
- scss/components/_resource.scss
- scss/global/_flex.scss
- templates/actor/actor-sheet.hbs
- templates/item/item-sheet.hbs
* fixed formatting from #147 
* added share text option from #141 
* fixed #155 in a way that does not break vehicles
> enhancement and bugfixes

- module/actor/actor.js
- module/util.js
- template.json
- templates/actor/actor-sheet.hbs
* replaced missing template file 
* fixed formatting to allow the notes tab to work.  #123 
* also fixed an issue where setting a numeric attribute to a random string will break stuff.  not it's just ignored.
> character notes tab fixed

- css/swse.css
- module/actor/attack.js
- scss/components/_attack.scss
> * added critical and fail indicators that include colorblind icons #149

- css/swse.css
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/actor/health.js
- module/config.js
- module/item/item.js
- module/swse.js
- scss/components/_attack.scss
- scss/components/_resource.scss
- system.json
- template.json
- templates/actor/actor-sheet.hbs
- templates/actor/parts/actor-health.hbs
- templates/actor/parts/actor-shields.hbs
- templates/actor/parts/attack/weapon-block.hbs
- templates/actor/vehicle-sheet.hbs
- templates/actor/vehicle/vehicle-health.hbs
* changed shield resolution
* added shield as a possible token stat
* added shield panel on character sheets and added controls
* added shield status toggle to character sheets #153 
* cleaned up overlapping CSS classes
> New Shield Implementation

- module/actor/attack-handler.js
- module/actor/attack.js
* Fixed bug where equipping a weapon to a clean character would leave a blank attack block. #229
* made item resolution more robust
> fixed bug that occurs when a fresh character equips a weapon

- css/swse.css
- module/actor/actor-sheet.js
- module/actor/actor.js
- module/compendium/compendium-browser.js
- module/compendium/compendium-directory.js
- module/settings/system.js
- module/swse.js
- scss/components/_compendium.scss
- scss/swse.scss
- templates/compendium/compendium-browser.hbs
- templates/compendium/compendium-browser_entry.hbs
- templates/compendium/compendium.hbs
> new compendium viewer with better searching

- module/actor/actor.js
- module/actor/attack-handler.js
- module/actor/attack.js
> fixed problems around dynamic switching of character to NPC or player

- module/actor/actor.mjs
This is the new (and discussed) approach to resolve the speed value of a token as int value for further calculations in other modules.
> Update actor.mjs to resolve speed as int in new getter

- module/actor/actor.mjs
- module/actor/skill-handler.mjs
- module/item/item-sheet.mjs
- templates/actor/parts/actor-classes.hbs
Fixes Issues: #412 and #413 
Additional fixes for multiclassing after 0.7.10
> Bug fixes misc

- module/actor/actor.mjs
- module/actor/attack.mjs
- module/actor/defense.mjs
Fixes:
- Allow implants on actors
- Fixes issue #415
- Fixes issue #424
> Patch - heroicLevel plus

- module/actor/actor.mjs
Fixes #380 
adds handling the grappleBonus attribute provided by Skilled Grappler
> add handling of grappleBonus

- module/actor/data/abstract.mjs
- module/actor/data/characterdata.mjs
- module/actor/data/templates/abilities.mjs
- module/actor/data/templates/attributes.mjs
- module/actor/data/templates/defenses.mjs
- module/actor/data/templates/details.mjs
- module/actor/data/templates/health.mjs
- module/actor/data/templates/shields.mjs
- module/actor/data/templates/skills.mjs
- module/actor/data/templates/traits.mjs
These are the inital Typedatamodel files for the character actor type. 
See #446 
These changes are not activated yet within the code and will not currently have any effects on running systems.
> add_initial_character_typedatamodel_files
